data:
  image_dir: data/images/images
  train_data: data/train_labels.csv
  test_data: data/sample_sub_v2.csv
  output: output.csv
  test_data_size: 509

model:
  load_trained_model: False
  saved_models_folder: saved_models
  saved_model: resnet_v2.pth
  model_type: resnet18

hyperparams:
  num_epochs: 50
  cross_validation_split: 0.2
  batch_size: 64
  learning_rate: 0.001
  num_workers: 2
  lr_scheduler:
    factor: 0.1
    patience: 5
