data:
  image_dir:
  data:
  train_data:
  output: output.csv
  test_data_size: 509

model:
  load_trained_model: False
  saved_models_folder: saved_models/

hyperparameters:
  num_epochs: 50
  cross_validation_split: 0.2
  batch_size: 64
  learning_rate: 0.01
  num_workers: 4
